name: 'C# Project Version Comparer'
description: 'Compares the version of different .csproj files'
author: 'Kenneth Fossen'

# Define your inputs here.
inputs:
  projects:
    description: 'List of projects to check version number for'
    required: true

# Define your outputs here.
outputs:
  equal:
    description: 'Boolean result'

runs:
  using: node20
  main: dist/index.js
