on: [pull_request, push]

permissions: read-all

jobs:
  project-version-cmp:
    runs-on: ubuntu-latest
    name: Compare C# Project files
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compare Project Files
        uses: ./ # Uses an action in the root directory
        id: solution
        with:
          projects: |-
            testdata/Client.csproj
            testdata/Schema.csproj

      # Use the output from the `solution` step
      - name: Get the output equal
        run: echo "Projects are equal ${{ steps.solution.outputs.equal }}"
